/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfacegrafica;

import cadastroalunos.CadastroAluno;
import dadosaluno.ControlaAluno;
import javabean.Aluno;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan e Jarrel
 */
public class DlgAlunos extends javax.swing.JDialog {

    /**
     * Creates new form DlgAlunos
     */
    
    ControlaAluno ca;
    
    public DlgAlunos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public DlgAlunos(java.awt.Frame parent, boolean modal, ControlaAluno ca) {
        super(parent, modal);
        this.ca = ca;
        initComponents();
        exibirInformacoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlunos = new javax.swing.JTable();
        btnTerceiroElemento = new javax.swing.JButton();
        btnPrimeiroEUltimo = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnIdade = new javax.swing.JButton();
        btnDadosCSV = new javax.swing.JButton();
        Topo = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 600));
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(750, 600));
        getContentPane().setLayout(null);

        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSair.setForeground(new java.awt.Color(0, 74, 127));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconVoltar.png"))); // NOI18N
        btnSair.setText("VOLTAR");
        btnSair.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(610, 510, 120, 40);

        tblAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Matricula", "D. De Nascimento", "Idade", "CPF", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(tblAlunos);
        tblAlunos.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 60, 630, 351);

        btnTerceiroElemento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTerceiroElemento.setForeground(new java.awt.Color(0, 74, 127));
        btnTerceiroElemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconImprimir.png"))); // NOI18N
        btnTerceiroElemento.setText("Terceiro Elemento");
        btnTerceiroElemento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 74, 127), 2));
        btnTerceiroElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerceiroElementoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTerceiroElemento);
        btnTerceiroElemento.setBounds(30, 440, 150, 40);

        btnPrimeiroEUltimo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPrimeiroEUltimo.setForeground(new java.awt.Color(0, 74, 127));
        btnPrimeiroEUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconImprimir.png"))); // NOI18N
        btnPrimeiroEUltimo.setText("Primeiro e Ultimo");
        btnPrimeiroEUltimo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        btnPrimeiroEUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroEUltimoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrimeiroEUltimo);
        btnPrimeiroEUltimo.setBounds(30, 490, 150, 40);

        btnRemover.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(0, 74, 127));
        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconDeletar.png"))); // NOI18N
        btnRemover.setText("Remover o Ultimo");
        btnRemover.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemover);
        btnRemover.setBounds(200, 490, 150, 40);

        btnIdade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIdade.setForeground(new java.awt.Color(0, 74, 127));
        btnIdade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconImprimir.png"))); // NOI18N
        btnIdade.setText("Verifica a idade");
        btnIdade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        btnIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(btnIdade);
        btnIdade.setBounds(200, 440, 150, 40);

        btnDadosCSV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDadosCSV.setForeground(new java.awt.Color(0, 74, 127));
        btnDadosCSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSalvar2.png"))); // NOI18N
        btnDadosCSV.setText("SALVAR DADOS EM CSV");
        btnDadosCSV.setActionCommand("Salvar Dados em CSV\n");
        btnDadosCSV.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        btnDadosCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosCSVActionPerformed(evt);
            }
        });
        getContentPane().add(btnDadosCSV);
        btnDadosCSV.setBounds(420, 510, 180, 40);

        Topo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Topo.png"))); // NOI18N
        getContentPane().add(Topo);
        Topo.setBounds(0, 0, 750, 120);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fundo.png"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 110, 750, 450);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exibirInformacoes(){
    
        ArrayList<Aluno> alunos = ca.retornarDados(); 
        
        for(int i = 0; i < alunos.size(); i++){
            
            tblAlunos.setValueAt("", i, 0);
            tblAlunos.setValueAt("", i, 1);
            tblAlunos.setValueAt("", i, 2);
            tblAlunos.setValueAt("", i, 3);
            tblAlunos.setValueAt("", i, 4);
            tblAlunos.setValueAt("", i, 5);
            
        }
        
        for(int i = 0; i < alunos.size(); i++){
            
            SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy"); 
            
            tblAlunos.setValueAt(alunos.get(i).getNome(), i, 0);
            tblAlunos.setValueAt(alunos.get(i).getMatricula(), i, 1);
            tblAlunos.setValueAt(dataFormatada.format(alunos.get(i).getDataNasc()), i, 2);
            tblAlunos.setValueAt(alunos.get(i).getIdade(), i, 3);
            tblAlunos.setValueAt(alunos.get(i).getCpf(), i, 4);
            tblAlunos.setValueAt(alunos.get(i).getTelefone(), i, 5);
            
        }
        
    }
    
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnTerceiroElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerceiroElementoActionPerformed
        ArrayList<Aluno> alunos = ca.retornarDados();
        
        int qtLista = alunos.size();
        
        StringBuilder terceiroElemento = new StringBuilder();

        try {
            if (alunos.get(2) != null) {
                
                SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy"); 
                
                terceiroElemento
                        .append("Nome: ").append(alunos.get(2).getNome())
                        .append("\nMatricula: ").append(alunos.get(2).getMatricula())
                        .append("\nData de Nasc.: ").append(dataFormatada.format(alunos.get(2).getDataNasc()))
                        .append("\nIdade: ").append(alunos.get(2).getIdade())
                        .append("\nTelefone: ").append(alunos.get(2).getTelefone())
                        .append("\nCPF: ").append(alunos.get(2).getCpf())
                        .append("\n\nQuantidade de elementos na lista: ").append(qtLista);
                JOptionPane.showMessageDialog(null, terceiroElemento);
            }
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Não existe elemento na terceira posição!");
        }
    }//GEN-LAST:event_btnTerceiroElementoActionPerformed
    
    /**
     * Método que retorna para o usuário o primeiro e último elemento.
     * 
     * @param btnPrimeiroEUltimoActionPerformed 
     */
    private void btnPrimeiroEUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroEUltimoActionPerformed
        ArrayList<Aluno> alunos = ca.retornarDados();
        
        StringBuilder primeiroUltimoElemento = new StringBuilder();
        
        try {
            if (alunos.size() >= 2) {
                SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy"); 
                
                int ultimoElemento = alunos.size() - 1;
                
                primeiroUltimoElemento
                        .append("Primeiro Elemento:\nNome: ").append(alunos.get(0).getNome())
                        .append("\nMatricula: ").append(alunos.get(0).getMatricula())
                        .append("\nData de Nasc.: ").append(dataFormatada.format(alunos.get(0).getDataNasc()))
                        .append("\nIdade: ").append(alunos.get(0).getIdade())
                        .append("\nTelefone: ").append(alunos.get(0).getTelefone())
                        .append("\nCPF: ").append(alunos.get(0).getCpf())
                        .append("\n\nUltimo Elemento:\nNome: ").append(alunos.get(ultimoElemento).getNome())
                        .append("\nMatricula: ").append(alunos.get(ultimoElemento).getMatricula())
                        .append("\nData de Nasc.: ").append(dataFormatada.format(alunos.get(ultimoElemento).getDataNasc()))
                        .append("\nIdade: ").append(alunos.get(ultimoElemento).getIdade())
                        .append("\nTelefone: ").append(alunos.get(ultimoElemento).getTelefone())
                        .append("\nCPF: ").append(alunos.get(ultimoElemento).getCpf());
                        
                JOptionPane.showMessageDialog(null, primeiroUltimoElemento);
            }else{
                
                SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy"); 
                
                primeiroUltimoElemento
                        .append("Nome: ").append(alunos.get(0).getNome())
                        .append("\nMatricula: ").append(alunos.get(0).getMatricula())
                        .append("\nData de Nasc.: ").append(dataFormatada.format(alunos.get(0).getDataNasc()))
                        .append("\nIdade: ").append(alunos.get(0).getIdade())
                        .append("\nTelefone: ").append(alunos.get(0).getTelefone())
                        .append("\nCPF: ").append(alunos.get(0).getCpf());
                JOptionPane.showMessageDialog(null, primeiroUltimoElemento);
            }
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Não existe elementos na lista!");
        }
    }//GEN-LAST:event_btnPrimeiroEUltimoActionPerformed
    
    /**
     * Método que remove o último elemento da lista.
     * 
     * @param btnRemoverActionPerformed 
     */
    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        ArrayList<Aluno> alunos = ca.retornarDados();
        
        if(alunos.isEmpty()) {
            JOptionPane.showMessageDialog(null,"A lista esta vazia");
        }else{
            int ultimoElemento = alunos.size()-1;
            alunos.remove(ultimoElemento);
            JOptionPane.showMessageDialog(null, "O ultimo elemento foi removido, feche a aba da lista e abra novamente");
        }
        
        this.dispose();
    }//GEN-LAST:event_btnRemoverActionPerformed
    
   
    private void btnIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdadeActionPerformed
        ArrayList<Aluno> alunos = ca.retornarDados();
        
        StringBuilder maiorMenor = new StringBuilder();
        
        int maior = 0, menor = 0, maiorPos=0, menorPos=0;
        
        for(int i=0; i<alunos.size();i++){
            
            if(i==0){
                int idadeInt = Integer.parseInt(alunos.get(i).getIdade());
                maior = idadeInt;
                menor = idadeInt;
                maiorPos = i;
                menorPos = i;
            }else{
                int idadeInt = Integer.parseInt(alunos.get(i).getIdade());
                if(maior<idadeInt){
                    maior = idadeInt;
                    maiorPos = i;
                }
                if(menor>idadeInt){
                    menor = idadeInt;
                    menorPos = i;
                }
            }
        }
        
        SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy"); 
        
        maiorMenor
                        .append("Mais novo:\nNome: ").append(alunos.get(menorPos).getNome())
                        .append("\nMatricula: ").append(alunos.get(menorPos).getMatricula())
                        .append("\nData de Nasc.: ").append(dataFormatada.format(alunos.get(menorPos).getDataNasc()))
                        .append("\nIdade: ").append(alunos.get(menorPos).getIdade())
                        .append("\nTelefone: ").append(alunos.get(menorPos).getTelefone())
                        .append("\nCPF: ").append(alunos.get(menorPos).getCpf())
                        .append("\n\nMais velho:\nNome: ").append(alunos.get(maiorPos).getNome())
                        .append("\nMatricula: ").append(alunos.get(maiorPos).getMatricula())
                        .append("\nData de Nasc.: ").append(dataFormatada.format(alunos.get(maiorPos).getDataNasc()))
                        .append("\nIdade: ").append(alunos.get(maiorPos).getIdade())
                        .append("\nTelefone: ").append(alunos.get(maiorPos).getTelefone())
                        .append("\nCPF: ").append(alunos.get(maiorPos).getCpf());
                        
                JOptionPane.showMessageDialog(null, maiorMenor);
        
        
    }//GEN-LAST:event_btnIdadeActionPerformed

    private void btnDadosCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosCSVActionPerformed
       ArrayList<Aluno> alunos = ca.retornarDados();
        
        File file = new File("ListagemAlunos.csv");
        FileWriter fw = null;
        SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy"); 
        
        try {
            fw = new FileWriter(file);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar os arquivos no formato csv.");
        }
        
        BufferedWriter bw = new BufferedWriter(fw);
        
        for(int i = 0; i < alunos.size();i++){
            try {
                bw.write(alunos.get(i).getMatricula()+",");
                bw.write(alunos.get(i).getNome()+"\t,");
                bw.write(alunos.get(i).getIdade()+", ");
                bw.write(dataFormatada.format(alunos.get(i).getDataNasc())+", ");
                bw.write(alunos.get(i).getTelefone()+", ");
                bw.write(alunos.get(i).getCpf()+" ");
                
                bw.newLine();
            } catch (IOException ex) {
               JOptionPane.showMessageDialog(null, "Erro ao salvar os arquivos no formato csv");
            }
        }
        
        try {
            bw.close();
        } catch (IOException ex) {
            //
        }
        
        try {
            fw.close();
            JOptionPane.showMessageDialog(null, "Dados salvos em CSV com sucesso!");
        } catch (IOException ex) {
            //
        }
    }//GEN-LAST:event_btnDadosCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgAlunos dialog = new DlgAlunos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Topo;
    private javax.swing.JButton btnDadosCSV;
    private javax.swing.JButton btnIdade;
    private javax.swing.JButton btnPrimeiroEUltimo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTerceiroElemento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlunos;
    // End of variables declaration//GEN-END:variables
}
