/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacegrafica;

import cadastroalunos.CadastroAluno;
import dadosaluno.ControlaAluno;
import javabean.Aluno;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Juan e Jarrel
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form interfacegrafica
     */
    ControlaAluno ca = new ControlaAluno();

    public TelaCadastro() {
        initComponents();
    }

    public TelaCadastro(ControlaAluno ca) {
        this.ca = ca;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        iconCadastrar = new javax.swing.JLabel();
        tfdMatricula = new javax.swing.JTextField();
        tfdIdade = new javax.swing.JTextField();
        tfdNome = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnTerceiraPosicao = new javax.swing.JButton();
        tfdTelefone = new javax.swing.JFormattedTextField();
        tfdCPF = new javax.swing.JFormattedTextField();
        jDateChooserNasc = new com.toedter.calendar.JDateChooser();
        Topo = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(765, 580));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 74, 127));
        jLabel3.setText("NOME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 180, 70, 25);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CADASTRO ALUNO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 20, 480, 64);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 74, 127));
        jLabel4.setText("MATRICULA:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 250, 120, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 74, 127));
        jLabel6.setText("D. DE NASCIMENTO:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 320, 200, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 74, 127));
        jLabel7.setText("IDADE:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 180, 80, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 74, 127));
        jLabel8.setText("TELEFONE:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 250, 110, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 74, 127));
        jLabel9.setText("CPF:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 320, 50, 25);

        iconCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconCadastrar.png"))); // NOI18N
        getContentPane().add(iconCadastrar);
        iconCadastrar.setBounds(90, 10, 330, 114);

        tfdMatricula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfdMatricula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        tfdMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(tfdMatricula);
        tfdMatricula.setBounds(70, 280, 280, 30);

        tfdIdade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfdIdade.setToolTipText("");
        tfdIdade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        tfdIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(tfdIdade);
        tfdIdade.setBounds(420, 210, 280, 30);

        tfdNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfdNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        tfdNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tfdNome);
        tfdNome.setBounds(70, 210, 280, 30);

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 74, 127));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSalvar.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(10, 490, 130, 40);

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(0, 74, 127));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconVoltar.png"))); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(620, 490, 120, 40);

        btnTerceiraPosicao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTerceiraPosicao.setForeground(new java.awt.Color(0, 74, 127));
        btnTerceiraPosicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconInserir.png"))); // NOI18N
        btnTerceiraPosicao.setText("INSERIR NA 3º POSIÇÃO");
        btnTerceiraPosicao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        btnTerceiraPosicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerceiraPosicaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTerceiraPosicao);
        btnTerceiraPosicao.setBounds(150, 490, 210, 40);

        tfdTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        try {
            tfdTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdTelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfdTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(tfdTelefone);
        tfdTelefone.setBounds(420, 280, 280, 30);

        tfdCPF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        try {
            tfdCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdCPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(tfdCPF);
        tfdCPF.setBounds(420, 350, 280, 30);

        jDateChooserNasc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        jDateChooserNasc.setDateFormatString("dd/MM/yyyy");
        jDateChooserNasc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jDateChooserNasc);
        jDateChooserNasc.setBounds(70, 350, 280, 30);

        Topo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Topo.png"))); // NOI18N
        getContentPane().add(Topo);
        Topo.setBounds(0, 0, 820, 160);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fundo.png"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 120, 750, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfdMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdMatriculaActionPerformed

    private void tfdIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdIdadeActionPerformed

    private void tfdNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdNomeActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        Aluno objAluno = new Aluno();

        objAluno.setNome(tfdNome.getText());
        objAluno.setMatricula(tfdMatricula.getText());
        objAluno.setDataNasc(jDateChooserNasc.getDate());
        objAluno.setIdade(tfdIdade.getText());
        objAluno.setTelefone(tfdTelefone.getText());
        objAluno.setCpf(tfdCPF.getText());

        if (objAluno.getNome() == null || objAluno.getMatricula() == null
                || objAluno.getDataNasc() == null || objAluno.getIdade() == null
                || objAluno.getTelefone() == null || objAluno.getCpf() == null) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else {
            if (ca.salvarDados(objAluno)) {
                JOptionPane.showMessageDialog(null, "Dados do aluno cadastrados!");
                tfdNome.setText("");
                tfdMatricula.setText("");
                jDateChooserNasc.setDate(null);
                tfdIdade.setText("");
                tfdTelefone.setText("");
                tfdCPF.setText("");
                tfdNome.requestFocus();
                 this.dispose();
            } else if (!ca.matriculaIgual(objAluno)) {
                JOptionPane.showMessageDialog(null, "Erro! matricula ja existente no sistema.");
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnTerceiraPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerceiraPosicaoActionPerformed

        Aluno objAluno = new Aluno();

        objAluno.setNome(tfdNome.getText());
        objAluno.setMatricula(tfdMatricula.getText());
        objAluno.setDataNasc(jDateChooserNasc.getDate());
        objAluno.setIdade(tfdIdade.getText());
        objAluno.setTelefone(tfdTelefone.getText());
        objAluno.setCpf(tfdCPF.getText());

        if (objAluno.getNome() == null || objAluno.getMatricula() == null
                || objAluno.getDataNasc() == null || objAluno.getIdade() == null
                || objAluno.getTelefone() == null || objAluno.getCpf() == null) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else {
            if (ca.salvarNa3POS(objAluno)) {
                JOptionPane.showMessageDialog(null, "Dados do aluno cadastrados!");
                tfdNome.setText("");
                tfdMatricula.setText("");
                jDateChooserNasc.setDate(null);
                tfdIdade.setText("");
                tfdTelefone.setText("");
                tfdCPF.setText("");
                tfdNome.requestFocus();
                this.dispose();
            } else if (!ca.matriculaIgual(objAluno)) {
                JOptionPane.showMessageDialog(null, "Erro! matricula ja existente no sistema.");
            }
        }
    }//GEN-LAST:event_btnTerceiraPosicaoActionPerformed

    private void tfdTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdTelefoneActionPerformed

    }//GEN-LAST:event_tfdTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Topo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnTerceiraPosicao;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel iconCadastrar;
    private com.toedter.calendar.JDateChooser jDateChooserNasc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField tfdCPF;
    private javax.swing.JTextField tfdIdade;
    private javax.swing.JTextField tfdMatricula;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JFormattedTextField tfdTelefone;
    // End of variables declaration//GEN-END:variables
}
